### ISSUE TITLE
"Are you A Romantic" - Capitalization Consistency

### ISSUE THREAD

**Issue by shickey** [blakesoftware-spring2016/bakken-quiz#169]
On the choose a quiz page, the romantic quiz title reads

"Are You A Romantic?"

On the quiz description page, it reads:

"Are you a Romantic?"

On the question pages, it reads:

"Are You a Romantic"

We need to figure out which is correct and update everywhere!

**Comment by kincaidoneil** [comment]
To fix this, we need to edit the PS files for the quiz description page and question page...does anyone know how to do that?

**Comment by shickey** [comment]
Julie and Juliet to discuss and confirm around 10am tomorrow

**Comment by shickey** [comment]
Proper capitalization is:

Are You a Romantic?
