### ISSUE TITLE
Romantic Quiz Results Background

### ISSUE THREAD

**Issue by crunchychips** [blakesoftware-spring2016/bakken-quiz#47]
The background displayed in the Romantic quiz results page is blue, as opposed to grey. The share results page is blue even if you are coming from the Romantic quiz, but I'm not sure if that is an issue.

**Comment by kincaidoneil** [comment]
@shickey What do you think on this? Should we have a different colored background depending upon the quiz?

**Comment by shickey** [comment]
My guts says probably. But we can ask the Bakken folks when they come to review. I'm assuming it wouldn't be a huge thing for us to change it back, yeah? So I say we do it to match the rest of the flow fo the application.
