### ISSUE TITLE
File not found 404 error on question page.

### ISSUE THREAD

**Issue by shickey** [blakesoftware-spring2016/bakken-quiz#60]
Each time the user navigates to a question, the JS console shows a 404 error being thrown from attempting to load an image from url `%7B%7Banswer.image%7D%7D`

![screen shot 2016-05-05 at 8 27 26 am](https://cloud.githubusercontent.com/assets/1489558/15044618/70ccf1ae-129b-11e6-87f9-2605467a138e.png)

**Comment by kincaidoneil** [comment]
Fixed by ecf5d99be9b4adad5e9a4f923423befc804e97a9.
