### ISSUE TITLE
Add popup prompt to timeout controller

### ISSUE THREAD

**Issue by kincaidoneil** [blakesoftware-spring2016/bakken-quiz#71]
Instead of just redirecting to touch to begin, prompt the user if they want to continue, and _then_ after an additional timeout, redirect to touch to begin. Its pretty jarring in the current implementation

And then lower the timeout to 30 seconds or something for production

**Comment by shickey** [comment]
One thing to be careful of here is that this popup should NOT occur if the touch to begin page is already up.
