### ISSUE TITLE
Touch Begin Animation

### ISSUE THREAD

**Issue by mthofstadte17** [blakesoftware-spring2016/bakken-quiz#93]

**Comment by mthofstadte17** [comment]
Text sliding in, more movement, "Touch Anywhere to Begin" more active

**Comment by kincaidoneil** [comment]
I fixed the issue where the images weren't loading (I used the blue text instead of gray). Is that okay? And was there anything else we wanted to do here, or can I close it?

**Comment by lagerasimov17** [comment]
Unless there are further enhancements for the touch to begin animation, I believe I finished/resolved this issue.
